#####
#
# Docker file to build image that can run Data Science Bowl 2017 tutorial:
# U-Net Segmentation Approach to Cancer Diagnosis
#

FROM tensorflow/tensorflow

MAINTAINER Wei-Yi Cheng

RUN pip install keras pandas && \
    rm -rf /root/.cache/pip/*

